language: go

go:
  - '1.11'

env:
  global:
    - GO111MODULE=on

go_import_path: arnested.dk/go/dsupdate

before_install:
  - GO111MODULE=off go get github.com/robertkrimen/godocdown/godocdown
  - GO111MODULE=off go get github.com/frapposelli/wwhrd
  - curl -sSL https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter

before_script:
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make doc ; git diff --quiet # Check the docs are up to date
  - go test -v -race -coverprofile=c.out -covermode=atomic ./...
  - ln c.out coverage.txt # Cover profile should be detected by both CodeClimate and CodeCov
  - go mod vendor && wwhrd check

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - bash <(curl -s https://codecov.io/bash)
