on: push
name: Build and Deploy
jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and test
      uses: cedrickring/golang-action/go1.11@master
      env:
        GO111MODULE: "on"
      with:
        args: go test -verbose -race -cover -covermode=atomic ./...
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
    - name: Authenticate to Google Cloud
      if: github.ref == 'refs/heads/master' && !github.deleted
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
    - name: Deploy to Google Cloud Functions
      if: github.ref == 'refs/heads/master' && !github.deleted
      uses: actions/gcloud/cli@master
      env:
        CF_NAME: ${{ secrets.CF_NAME }}
        CF_PROJECT: ${{ secrets.CF_PROJECT }}
        CF_REGION: ${{ secrets.CF_REGION }}
        ENTRY_POINT: Handle
        MEMORY: 128M
        RUNTIME: go111
      with:
        args: functions deploy ${CF_NAME} --project=${CF_PROJECT} --region=${CF_REGION}
          --entry-point=${ENTRY_POINT} --runtime=${RUNTIME} --trigger-http --memory=${MEMORY}
          --format='yaml(status,updateTime,versionId)'
