on: push
name: Build and Deploy
jobs:
  check_not_deleted:
    runs-on: ubuntu-latest
    steps:
    - name: If deleted
      if: 'github.event.deleted'
      run: exit
  build_and_test:
    name: Build and test
    needs: check_not_deleted
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and test
      uses: cedrickring/golang-action/go1.11@master
      env:
        GO111MODULE: "on"
      with:
        args: go test -verbose -race -cover -covermode=atomic ./...
  check_master:
    runs-on: ubuntu-latest
    steps:
    - name: If not master
      if: github.ref != 'refs/heads/master'
      run: exit
  deploy:
    name: Deploy
    needs:
    - check_not_deleted
    - check_master
    - build_and_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Authenticate to Google Cloud
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
    - name: Deploy to Google Cloud Functions
      uses: actions/gcloud/cli@master
      with:
        args: functions deploy ${{secrets.CF_NAME}} --project=${{secrets.CF_PROJECT}} --region=${{secrets.CF_REGION}}
          --entry-point=Handle --runtime=go111 --trigger-http --memory=128M
          --format='yaml(status,updateTime,versionId)'
